blog:
  pattern:  /blog
  defaults: { _controller: BlogBundle:Default:index }

blog_new:
  pattern:  /blog/new
  defaults: { _controller: BlogBundle:Default:new }

blog_create:
  pattern:  /blog/create
  defaults: { _controller: BlogBundle:Default:create }
