app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   aaaaaaaaaaaaaaaaaaaaaa
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    session:
        default_locale: ja_JP
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
    dbname:   symfony2
    user:     root
    password: ~

doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        BlogBundle: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
